CREATE INDEX IF NOT EXISTS idx_api_keys_user_id ON api_keys(user_id);
CREATE INDEX IF NOT EXISTS idx_events_environment_id ON events(environment_id);
CREATE INDEX IF NOT EXISTS idx_image_update_repository ON image_updates(repository);
CREATE INDEX IF NOT EXISTS idx_image_update_tag ON image_updates(tag);
CREATE INDEX IF NOT EXISTS idx_volume_backups_volume_name ON volume_backups(volume_name);
CREATE INDEX IF NOT EXISTS idx_vulnerability_ignores_env ON vulnerability_ignores(environment_id);
CREATE INDEX IF NOT EXISTS idx_vulnerability_ignores_vuln ON vulnerability_ignores(vulnerability_id);
CREATE INDEX IF NOT EXISTS idx_vulnerability_scans_status ON vulnerability_scans(status);

DROP INDEX IF EXISTS idx_vulnerability_ignores_env_vulnerability_id;
DROP INDEX IF EXISTS idx_events_environment_timestamp;
DROP INDEX IF EXISTS idx_image_updates_repository_tag;
DROP INDEX IF EXISTS idx_image_builds_environment_status;
DROP INDEX IF EXISTS idx_image_builds_environment_created_at;
DROP INDEX IF EXISTS idx_volume_backups_volume_name_created_at;
DROP INDEX IF EXISTS idx_compose_templates_lookup_description;
DROP INDEX IF EXISTS idx_compose_templates_lookup_name;
DROP INDEX IF EXISTS idx_projects_dir_name_not_null;
DROP INDEX IF EXISTS idx_projects_path;
DROP INDEX IF EXISTS idx_gitops_syncs_environment_project_id;
DROP INDEX IF EXISTS idx_gitops_syncs_environment_repository_id;
DROP INDEX IF EXISTS idx_gitops_syncs_environment_last_sync_status;
DROP INDEX IF EXISTS idx_gitops_syncs_auto_sync_true;
DROP INDEX IF EXISTS idx_gitops_syncs_environment_auto_sync;
DROP INDEX IF EXISTS idx_git_repositories_auth_type;
DROP INDEX IF EXISTS idx_git_repositories_enabled_url;
DROP INDEX IF EXISTS idx_vulnerability_ignores_env_created_at;
DROP INDEX IF EXISTS idx_vulnerability_scans_status_total_count;
DROP INDEX IF EXISTS idx_api_keys_user_managed_by_created_at;
DROP INDEX IF EXISTS idx_api_keys_expires_at_not_null;
DROP INDEX IF EXISTS idx_environments_enabled_true;
DROP INDEX IF EXISTS idx_environments_access_token_not_null;
